[project]
name = "fastapi-meal-planner-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "fastapi==0.135.1",
    "passlib==1.7.4",
    "pydantic[email]==2.12.5",
    "pydantic-settings==2.13.1",
    "python-jose==3.3.0",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.41.0",
    "psycopg[binary]>=3.3.3",
    "python-multipart>=0.0.22",
    "alembic>=1.18.4",
    "anthropic>=0.93.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
